Criação do Unpack (Mapa Mental e Diagrama de Causa e Efeito)
UnBArqDsw2023-2/2023.2_G3_ProjetoAmazon pull request #18
Opened 2023-09-14 03:38 UTC by SamuelGSouza

Criação do mapa mental e do diagrama de causa e efeito.

Closes #2

2023-09-14 04:25 UTC, oo7gabriel commented on docs/Base/causaEfeito.md
> +<figcaption align="center">Figura 1: Diagrama de causa e efeito. Fonte: (Pedro Henrique e Samuel Gomes)</figcaption>
Adicionar na fonte o ano que fizeram no caso 2023 , log depois dos nomes

2023-09-14 04:29 UTC, oo7gabriel commented on docs/Base/causaEfeito.md
> +|    Data    | Versão |      Descrição       |   Autor(es)    |
Adicionar os revisores do artefato

2023-09-14 04:30 UTC, oo7gabriel commented on docs/Base/mapaMental.md
> +## Referências Bibliograficas
Mudar título para bibliografia

2023-09-14 04:30 UTC, oo7gabriel commented on docs/Base/mapaMental.md
> +|    Data    | Versão |      Descrição       |   Autor(es)    |
Adicionar revisores do artefato

2023-09-14 04:32 UTC, oo7gabriel requested changes
Existem mudanças a serem feitas

2023-09-15 01:37 UTC, oo7gabriel approved these changes
Correção realizada

2023-09-15 01:38 UTC, HenriPucci approved these changes

2023-09-15 01:40 UTC, merged